# -*- coding: utf-8 -*-
{
    'name': 'MindDX Lokalizasyon',
    'version': '19.0.1.0.0',
    'installable': True,
    'application': True,
    'author': 'MindDX Digital Dönüşüm Teknolojileri A.Ş.',
    'summary': 'Lokalizasyon',
    'description': "",
    'depends': [
        'base',
        'account',
        'stock_account',
        'sale_stock',
        'hr',
        'purchase',
        'stock',
        'stock_delivery',
        'mail',
        'l10n_tr',
        # 'web',
    ],
    'category': 'Localization',
    # 'web.assets_backend': [
    #     'edonusum/static/src/js/license_validation.js',
    # ],
    # 'assets': {
    #     'web.assets_backend': [
    #         'edonusum/static/src/js/highlight_missing_fields.js',
    #     ],
    # },
    # 'assets': {
    #     'web.assets_backend': [
    #         'edonusum/static/src/js/display_notification.js',
    #     ],
    # },
    # 'web.assets_backend': [
    #     'edonusum/static/src/js/license_key_visibility.js',
    # ],
    'assets': {
        'web.assets_backend': [
            'edonusum/static/src/css/gelen_fatura_colors.css',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'security/mdx_gelen_fatura_security.xml',
        'data/initial_data.xml',
        'report/mdx_account_move_report.xml',
        'report/mdx_report_payment_receipt_templates.xml',
        # 'views/mdx_inh_res_config_settings_views.xml', # LICENSE_KEY
        'views/mdx_belge_cinsi_views.xml',
        'views/mdx_ebelge_senaryo_views.xml',
        'views/mdx_ebelge_tipi_views.xml',
        'views/mdx_ebelge_turu_views.xml',
        'views/mdx_fatura_alt_tipi_views.xml',
        'views/mdx_kod_liste_alt_tipi_views.xml',
        'views/mdx_kod_liste_tipi_views.xml',
        'views/mdx_kod_listesi_views.xml',
        'views/mdx_sabit_kod_views.xml',
        'views/mdx_fatura_seri_views.xml',
        'views/mdx_web_service_views.xml',
        'views/mdx_dokuman_sayac_views.xml',
        'views/mdx_edefter_doctype_desc_views.xml',
        # 'views/mdx_prozon_api_test_views.xml',
        'views/mdx_lokalizasyon_menu_views.xml',
        'views/mdx_inh_res_company_views.xml',
        'views/mdx_inh_res_partner_views.xml',
        'views/mdx_inh_account_move_views.xml',
        'views/mdx_inh_stock_picking_views.xml',
        # 'views/mdx_inh_project_task_views.xml',
        'views/mdx_inh_res_currency_views.xml',
        'views/mdx_gelen_fatura_views.xml',
        'views/mdx_gelen_irsaliye_views.xml',
        'views/mdx_inh_account_payment_views.xml',
        'views/mdx_edefter_views.xml',
        # 'views/mdx_inh_sale_order_views.xml',
        # 'views/mdx_inh_purchase_order_views.xml',
        'views/mdx_cheque_book_views.xml',
        'views/mdx_inh_account_menuitem.xml',
        'views/mdx_inh_stock_menuitem.xml',
        'data/cron_jobs.xml',
        'data/partner_ledger.xml',
        'views/mdx_yilsonu_kapanish_wizard_views.xml',
        'views/mdx_yilsonu_rapor_views.xml',
        'views/mdx_yilsonu_kapanish_run_views.xml',

    ],
    'license': 'LGPL-3',
}
